FEATURE: Add wildcard option to include all categories
discourse/discourse-zendesk-plugin pull request #24
Opened 2021-04-16 17:32 UTC by samamorgan

This commit adds the option to use a wildcard "*" to enable ticket creation for all categories.

2021-04-23 16:19 UTC, techAPJ commented on config/locales/client.en.yml
> +    zendesk_all_categories: Create tickets for all categories? If enabled, `zendesk_enabled_categories` are ignored.
I recommend changing the setting name to `zendesk_enable_all_categories`.

Also, let's replace the question mark `?` with period `.` in setting description for the sake of consistency.

2021-04-23 16:19 UTC, techAPJ requested changes
Added a minor feedback. Thanks for this PR.

2021-04-23 16:26 UTC, samamorgan commented
@techAPJ Great suggestions! Done.

2021-04-24 14:58 UTC, techAPJ approved these changes
Looks good. 👍🏼

2021-04-24 15:00 UTC, techAPJ commented
Thanks @samamorgan. ❤️

2021-04-24 15:00 UTC, merged